### ISSUE TITLE
Custom font Problem ! 

### ISSUE THREAD

**Issue by emadph** [apl-devs/AppIntro#422]
**AppIntro Version** : 4.1.0 
**Device/Android Version**: any device ...Huawei y511

addSlide(AppIntroFragment.newInstance(getResources().getString(R.string.intro_title1),
                getResources().getString(R.string.intro_font),          // not working !
                getResources().getString(R.string.intro_desc1), 
                getResources().getString(R.string.intro_font_desc),   // not working !
                R.drawable.explore_intro,
                getResources().getColor(R.color.intro),
                getResources().getColor(R.color.intro_title),
                getResources().getColor(R.color.intro_desc)));

setSkipTextTypeface(getResources().getString(R.string.intro_font));          // working 

-----------------------------------------------------
    <string name="intro_font">fonts/sansmobilebold.ttf</string>

by the way ... i saw all issues but non of them worked for me ...

and font exist in assets! 

English is not my mother tongue; please excuse any errors on my part

**Comment by avluis** [comment]
Don't specify a path to the font (they do go in the assets folder, so that is good), rather describe them like so: `<string name="title_font">nemoy_medium.ttf</string>` (be sure to get capitalization correct)
When it is time to load them in, make use of: `getResources().getString(R.string.title_font)`

The must also be loaded into the appropriately overloaded method (follow the source code here to find out which if in doubt).

**Comment by emadph** [comment]
@avluis  thx for quick resp.
actually i try both way u suggest but no luck ...(sting & getReso...)

(follow the source code here to find out which if in doubt )
which part of source you mention ?

**Comment by peter9870** [comment]
I also have the same issue, setting a custom font on the title and description does not work for me. I personally have my ttf files in assets/fonts/ however it still doesn't work with the font files in the assets folder. Although I'd expect it to still work by specifying "fonts/Roboto-Light.ttf".

**Comment by ahmadzarei** [comment]
I think I find the problem
In AppIntroBaseFragment.JAVA
Line number 89 and 98 is wrong check 

`if (titleTypeface != null && titleTypeface.equals("")) {`
`if (descTypeface != null && descTypeface.equals("")) {`

when we set custom font for title or description then titleTypeface.equals("") or descTypeface.equals("")
always return false therefor if body never run.

**Comment by avluis** [comment]
Well hello! Duh!
I see what the issue is -- @ahmadzarei thank you.

The issue above was fixed on this commit: e36697c08
But said fix has not been pushed to maven...

So if you guys want to get the most up to date code, I recommend grabbing AppIntro via JitPack:
https://jitpack.io/#paolorotolo/AppIntro

**Comment by ahmadzarei** [comment]
@avluis thx for resp.
I try to use JitPack by below codes in gradle:
`allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}`
`compile 'com.github.paolorotolo:AppIntro:v4.1.0'`

but the problem not solved in downloaded files, there is no change in line 89 and 98.
Help me plz.

**Comment by avluis** [comment]
@ahmadzarei You have to grab the most up to date code so you are looking for snapshots:
https://jitpack.io/#paolorotolo/AppIntro/master-SNAPSHOT

**Comment by emadph** [comment]
tanks guys ...

**Comment by emadph** [comment]
Sry for opening  issue again ... 
but after i used @ahmadzarei SNAPSHOT ... face with new issue in proguardFiles...
anyway ... what should i do ?! 
use master or snapshot ?!

**Comment by avluis** [comment]
@emadph What's wrong with Proguard?
You need to give error snippets so that I can work without guessing.
Can you post your project `build.gradle` (including your proguard config)?

Stay on the SNAPSHOT build and I can push out a fix for whatever issue you are having or at least find out what issue you are having.

**Comment by emadph** [comment]
@avluis  
logcat : 
----------------------


  java.lang.Error: Can not init easingMethod instance
                                                                                 at com.daimajia.easing.c.a(Skill.java:107)
                                                                                 at com.daimajia.easing.b.a(Glider.java:37)
                                                                                 at com.daimajia.easing.b.a(Glider.java:33)
                                                                                 at com.daimajia.androidanimations.library.i.a.a.a(DropOutAnimator.java:14)
                                                                                 at com.daimajia.androidanimations.library.a.b(BaseViewAnimator.java:50)
                                                                                 at com.daimajia.androidanimations.library.c.a(YoYo.java:152)
                                                                                 at com.daimajia.androidanimations.library.c.a(YoYo.java:36)
                                                                                 at com.daimajia.androidanimations.library.c$a.a(YoYo.java:106)
                                                                                 at com.viksaa.sssplash.lib.a.a.e(AwesomeSplash.java:207)
                                                                                 at com.viksaa.sssplash.lib.a.a$3.b(AwesomeSplash.java:177)
                                                                                 at com.d.a.c$a.b(AnimatorSet.java:756)
                                                                                 at com.d.a.m.e(ValueAnimator.java:1034)
                                                                                 at com.d.a.m.c(ValueAnimator.java:43)
                                                                                 at com.d.a.m$a.handleMessage(ValueAnimator.java:669)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:136)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5021)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643)
                                                                                 at dalvik.system.NativeStart.main(Native Method)


----------------------

Proguard File

-----------------

-keepattributes *Annotation*
-keepattributes SourceFile,LineNumberTable



# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
-keepclassmembers class fqcn.of.javascript.interface.for.webview {
   public *;
}

-keep class uk.co.chrisjenx.calligraphy.* { *; }
-keep class uk.co.chrisjenx.calligraphy.*$* { *; }

-dontwarn com.squareup.okhttp.**
-keep class .R
-keep class **.R$* {
    <fields>;
}

-keep class com.wang.avi.** { *; }
-keep class com.wang.avi.indicators.** { *; }

-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public enum com.bumptech.glide.load.resource.bitmap.ImageHeaderParser$** {
  **[] $VALUES;
  public *;


}


-----------------

**Comment by avluis** [comment]
@emadph https://github.com/daimajia/AnimationEasingFunctions#tips

**Comment by emadph** [comment]
it works like a charm...
